# Generated by Django 4.1.7 on 2023-03-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appareils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='devices/')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('duree', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.category')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.marques')),
            ],
        ),
    ]
