# Generated by Django 4.1.7 on 2023-03-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_appareils_temps_estime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='marques',
            options={'ordering': ['name']},
        ),
    ]
